export enum DomainErrorCode {
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  PASSWORD_AND_PASSWORD_REPEAT_NOT_EQUALS = 'PASSWORD_AND_PASSWORD_REPEAT_NOT_EQUALS',
}
